[[param]]
name = "database_dir"
type = "String"
doc = "The location of the database file."

[[param]]
name = "macaroon"
type = "String"
doc = "The location of the macaroon file."

[[param]]
name = "cert"
type = "String"
doc = "The location of the tls certificate file."

[[param]]
name = "listen_port"
type = "u16"
doc = "The port to listen on."

[[param]]
name = "amount"
type = "u64"
doc = "Minimal amount of boosts to show."

[[param]]
name = "lnd_url"
type = "String"
doc = "The url and port of the LND grpc api."
