[[param]]
name = "database_dir"
type = "String"
doc = "The location of the database file."

[[param]]
name = "play_sound_transactions"
type = "String"
doc = "Play sound with regular incoming transactions."

[[param]]
name = "macaroon"
type = "String"
doc = "The location of the macaroon file."

[[param]]
name = "cert"
type = "String"
doc = "The location of the tls certificate file."

[[param]]
name = "listen_port"
type = "u16"
doc = "The port to listen on."

[[param]]
name = "lnd_url"
type = "String"
doc = "The url and port of the LND grpc api."
