version: "3.7"

services:
  web:
    image: podcastindexorg/podcasting20-helipad:latest@sha256:6623c81feb203073360b00e9f3df69e8a72e6909169ec11804b171935f4359ee
    init: true
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    ports:
      - ${APP_HELIPAD_PORT}:2112
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${LND_DATA_DIR}:/lnd:ro
    environment:
      LND_URL: "$LND_IP:$LND_GRPC_PORT"
    networks:
      default:
        ipv4_address: $APP_HELIPAD_IP
