name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: ["v[0-9]+.[0-9]+.[0-9]*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare
      id: prep
      run: |
        VERSION=latest

        # If this is git tag, use the tag name as a docker tag
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi

        # Set output parameters.
        echo ::set-output name=version::${VERSION}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        tags: |
          ghcr.io/${{github.repository}}:${{steps.prep.outputs.version}}
          ghcr.io/${{github.repository}}:latest
